### ISSUE TITLE
When will the dataset be available?

### ISSUE THREAD

**Issue by zhanhl316** [dair-iitd/FloDial#1]
Hi Dear Authors,

      Your work is quite interesting and I think that would have huge impact! I would like to folow your work and your papers on this flowchat grounded dataset. May I know when it will be available?  Thank you very much!

Best,
Haolan

**Comment by DineshRaghu** [comment]
Dear Haolan, I am glad that you found our work interesting :)
We should release the dataset in a week or so.

**Comment by DineshRaghu** [comment]
@zhanhl316 The dialogs and the knowledge sources have been added to the `dataset` branch.
