### ISSUE TITLE
When will the evaluation be available?

### ISSUE THREAD

**Issue by YovaKem** [dair-iitd/FloDial#2]

**Comment by DineshRaghu** [comment]
@YovaKem Thank you for your interest in this work! We are working on the evaluation page where you can submit your model and get the results on the hidden test set. The page should be available in less than 2 weeks.

**Comment by YovaKem** [comment]
Hi @DineshRaghu, has the page become available? I'm still not seeing anything at https://dair-iitd.github.io/FloDial/

Thanks.

**Comment by YovaKem** [comment]
Hi @DineshRaghu, since you already inadvertently (I'm guessing) released the test data [here](https://github.com/dair-iitd/FloNet/blob/main/data/saved_data/cached_in_domain_hard_dialogs.pkl) can you just add it to this repo too? I can get the dialogs from the data cache, but I would also like to be able to evaluate retrieval over the gold-standard grounding labels.

**Comment by ashantanu** [comment]
Hi @YovaKem , we have added the test data in this repo now. Feel free to use it and let us know if there's any discrepancy. The pickle file you mentioned already has the processed data as well.
