### ISSUE TITLE
Number of data points

### ISSUE THREAD

**Issue by YovaKem** [dair-iitd/FloDial#3]
The paper says that 2,738 dialogs were created, but there are only 1,844 dialogs in `dialogs.json`. Is the number cited in the paper wrong, or has there been a bug in the data release? Thanks.

**Comment by DineshRaghu** [comment]
@YovaKem The dataset has a total of 2,738 dialogs. This repository only contains the `train` and the `validation` sets of both the *S-Flo* and the *U-Flo* split as the `test` sets are hidden. Hence there are only 1,844 dialogs.
